### ISSUE TITLE
Warning with React 15

### ISSUE THREAD

**Issue by karevn** [jsdf/coffee-react#36] opened 2016-04-14 05:56 UTC
When using CJSX with React 15, a warning is issued:

```
Warning: React.__spread is deprecated and should not be used.
```

**Comment by wordofchristian** [comment] 2016-04-26 21:32
Duplicate of #34

**Comment by jsdf** [comment] 2016-04-30 00:53
Fixed in https://github.com/jsdf/coffee-react/tree/v5.0.0

**Closed by jsdf** 2016-04-30 00:53 UTC
