### ISSUE TITLE
ReactClass does not have the displayName property?

### ISSUE THREAD

**Issue by xiaoDC** [jsdf/coffee-react#26] opened 2015-06-24 14:30 UTC
I use 'coffee-react' compile my *.cjsx files , and the compiled .js files are ok. But , in the complied .js files, ReactClass does not have the displayName property. Then in chrome dev tools with FaceBook React Developer Tools, I can't see the components name. 
![1](https://cloud.githubusercontent.com/assets/6940993/8332440/8a4e9a5c-1ac0-11e5-8fbd-2d94a49f7573.png)

**Comment by jsdf** [comment] 2015-06-27 07:16
dupe of https://github.com/jsdf/coffee-react/issues/11

**Closed by jsdf** 2015-06-27 07:16 UTC

**Comment by xiaoDC** [comment] 2015-06-27 07:21
thanks
